info:
  app:
    name: VR - Mini Autorizador
    version: '@project.version@'
    description: VR - Mini Autorizador
spring:
  application:
    name: vr-mini-autorizador
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/miniautorizador"
    username: root
    password:
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    openInView: 'true'
    show_sql: 'true'